'use strict'

// Hand-written entry point of @fugle/marketdata (`main` in package.json).
//
// `index.js` is generated by NAPI-RS and loads the native binding; it is
// re-exported as is (in this exact form, so Node's ESM loader still finds its
// named exports) and only the 1.x compatibility below is added on top.
module.exports = require('./index.js')

const { StockWebSocketClient, FutOptWebSocketClient } = module.exports

// ---------------------------------------------------------------------------
// For 1.x compatibility: a failed connect() does not end the process (#307)
// ---------------------------------------------------------------------------
//
// Why: the 1.x README connects with
//
//     stock.connect().then(() => stock.subscribe({ ... }))
//
// and no `.catch`. In 1.x a connection that could not be made (refused, TLS,
// authentication timeout) only emitted `error`; the Promise never settled, so
// with an `error` listener the program kept running. 3.0 rejects the Promise,
// and the promise `.then()` returns rejects in turn, unhandled: Node ends the
// process on an unhandled rejection.
//
// What: connect() returns a ConnectPromise. A rejection is *swallowed* — the
// promises it reaches are marked handled, so no `unhandledRejection` — only
// when all of these hold:
//
//   1. It is the connect failure itself. Its reason is remembered by identity
//      when connect() rejects, and only a promise rejected with that very
//      value is marked.
//   2. The promise is connect()'s own, or one reached from it only through
//      `.then(f)` calls without a rejection handler, any number of them
//      (`.then(f).then(g)`): those pass the rejection on unchanged, which is
//      the 1.x README's shape. Each ConnectPromise records whether it is one
//      (`chained`); a promise derived through anything else is not, and
//      neither is any promise derived from it.
//   3. The client had an `error` listener when connect() was called or when
//      it rejected. Both, because 1.x code often adds the listener after
//      calling connect(), and a `once('error')` listener is already gone when
//      connect() rejects: the `error` event comes first. In 1.x an `error`
//      with no listener threw from the EventEmitter, so a program without one
//      did not survive the failure either.
//   4. It is an `Error`. Rejected credentials reject with the server's `data`
//      object, as in 1.x, which did not catch that rejection either.
//
// What is deliberately not swallowed:
//   - an error thrown by `f` in `.then(f)`: a different value, the caller's
//     bug, unhandled as usual;
//   - anything without an `error` listener, and rejected credentials (3, 4);
//   - `await connect()`, `.catch(r)`, `.then(f, r)`: the caller handles the
//     rejection — they all still receive it, as 3.0 documents;
//   - `.finally()`, `Promise.all([connect()])`, `Promise.race(...)` and the
//     like, and anything chained after them or after `.catch(r)` /
//     `.then(f, r)` (say a `.catch(r)` that rethrows): they reject unhandled
//     unless the caller catches them (rule 2). 1.x code did not chain those
//     on a Promise that, on failure, never settled.
//
// The failures this covers are also reported through the `error` event,
// except `2010` (connect() aborted by disconnect()) and `2011` (already
// connected), which only reject; neither ended a 1.x program either.

/** Connect failures whose rejection is swallowed (rule 1). */
const swallowed = new WeakSet()
/** ConnectPromises a swallowed failure may be swallowed on (rule 2). */
const chained = new WeakSet()
const noop = () => {}
// Marks `promise` handled without passing it through ConnectPromise#then.
const markHandled = (promise) => Promise.prototype.then.call(promise, undefined, noop)
const isError = (value) => Object.prototype.toString.call(value) === '[object Error]'

class ConnectPromise extends Promise {
  then(onFulfilled, onRejected) {
    const derived = super.then(onFulfilled, onRejected)
    if (chained.has(this) && typeof onRejected !== 'function') {
      chained.add(derived)
      // Rule 2: a rejection of this promise reaches `derived` unchanged. This
      // runs in the same microtask checkpoint as `derived` rejecting, before
      // Node looks for unhandled rejections.
      Promise.prototype.then.call(this, undefined, (reason) => {
        if (swallowed.has(reason)) markHandled(derived)
      })
    }
    return derived
  }
}

for (const Client of [StockWebSocketClient, FutOptWebSocketClient]) {
  const nativeConnect = Client.prototype.connect
  Client.prototype.connect = function connect() {
    const client = this
    // Rule 3: a listener present now counts, even if it is gone by then.
    const hadErrorListener = client.listenerCount('error') > 0
    const pending = nativeConnect.apply(client, arguments)
    const promise = new ConnectPromise((resolve, reject) => {
      pending.then(resolve, (reason) => {
        reject(reason)
        // Rules 3 and 4.
        if (isError(reason) && (hadErrorListener || client.listenerCount('error') > 0)) {
          swallowed.add(reason)
          markHandled(promise)
        }
      })
    })
    chained.add(promise)
    return promise
  }
}
