#!/usr/bin/env python3
"""Tests for scripts/release-versions.py.

Run with either of:

    python3 scripts/test_release_versions.py
    python3 -m pytest scripts/test_release_versions.py

Every test builds a throwaway repository skeleton (the nine manifests, the
generated files and the two docs) in a temp directory and points the script's
ROOT at it, so nothing here touches the real tree.
"""
from __future__ import annotations

import contextlib
import importlib.util
import io
import json
import sys
import tempfile
import tomllib
import unittest
import unittest.mock
from pathlib import Path

SCRIPT = Path(__file__).resolve().with_name("release-versions.py")
spec = importlib.util.spec_from_file_location("release_versions", SCRIPT)
rv = importlib.util.module_from_spec(spec)
sys.modules[spec.name] = rv  # dataclasses resolve annotations through sys.modules
spec.loader.exec_module(rv)

BINDINGS, RUST, UNIFFI = "3.0.0-rc.4", "0.9.0-rc.3", "0.2.0-rc.3"

# Prose that names *old* versions on purpose. It mirrors MIGRATION-0.9.md,
# whose body is a historical narrative; only the title carries the current
# versions. A regression that scans the whole file shows up as a failure in
# TestMigrationHistory below.
MIGRATION_BODY = """
## Removed fields

3.0.0-rc.1 to rc.4 dropped all of these; rc.4 silently mishandled the
examples that 3.0.0-rc.2 documented. `pip install fugle-marketdata==3.0.0rc1`
still resolves for anyone pinned to the old line.
"""


def index_js(version: str, sites: int = 3) -> str:
    block = (
        "        if (bindingPackageVersion !== '%s' && process.env.NAPI_RS_ENFORCE_VERSION_CHECK) {\n"
        "          throw new Error(`Native binding package version mismatch, expected %s but got ${bindingPackageVersion}.`)\n"
        "        }\n"
    ) % (version, version)
    return "/* auto-generated by NAPI-RS */\n" + block * sites


def cargo_lock(bindings: str, rust: str, uniffi: str) -> str:
    entries = {
        "fugle-marketdata-core": rust,
        "fugle-marketdata": rust,
        "marketdata-uniffi": uniffi,
        "marketdata-py": bindings,
        "marketdata-js": bindings,
        "serde": "1.0.0",
    }
    return 'version = 4\n\n' + "".join(f'[[package]]\nname = "{n}"\nversion = "{v}"\n\n' for n, v in entries.items())


def write_repo(root: Path, bindings=BINDINGS, rust=RUST, uniffi=UNIFFI, *, generated=None, docs=None) -> None:
    """Write a consistent skeleton; `generated`/`docs` override the derived versions."""
    g = {"bindings": bindings, "rust": rust, "uniffi": uniffi, **(generated or {})}
    d = {"bindings": bindings, "rust": rust, "uniffi": uniffi, **(docs or {})}
    pep = rv.semver_to_pep440
    files = {
        "Cargo.toml": f"""[workspace]
members = ["core", "py", "js", "uniffi", "rust"]
resolver = "2"

[workspace.package]
version = "{bindings}"
edition = "2021"

[workspace.dependencies]
# comment with version = "9.9.9" that must not be touched
marketdata-core = {{ path = "core", package = "fugle-marketdata-core", version = "{rust}" }}
serde = {{ version = "1.0", features = ["derive"] }}
""",
        "js/package.json": json.dumps({"name": "@fugle/marketdata", "version": bindings, "napi": {}}, indent=2) + "\n",
        "py/pyproject.toml": f"""[build-system]
requires = ["maturin>=1.11,<2.0"]

[project]
name = "fugle-marketdata"
version = "{pep(bindings)}"

[tool.maturin]
version = "not-a-version"
""",
        "core/Cargo.toml": f'[package]\nname = "fugle-marketdata-core"\nversion = "{rust}"\n\n[dependencies]\nserde = {{ version = "1" }}\n',
        "rust/Cargo.toml": f'[package]\nname = "fugle-marketdata"\nversion = "{rust}"\n',
        "uniffi/Cargo.toml": f'[package]\nname = "marketdata-uniffi"\n# decoupled on purpose\nversion = "{uniffi}"\n',
        "py/Cargo.toml": '[package]\nname = "marketdata-py"\nversion.workspace = true\n',
        "js/Cargo.toml": '[package]\nname = "marketdata-js"\nversion.workspace = true\n',
        "bindings/csharp/MarketdataUniffi/MarketdataUniffi.csproj": f"<Project>\n  <PropertyGroup>\n    <Version>{uniffi}</Version>\n  </PropertyGroup>\n</Project>\n",
        "bindings/java/build.gradle.kts": f'group = "tw.com.fugle"\nversion = providers.gradleProperty("projectVersion").getOrElse("{uniffi}")\n',
        # generated
        "js/index.js": index_js(g["bindings"]),
        "js/package-lock.json": json.dumps(
            {"name": "@fugle/marketdata", "version": g["bindings"], "packages": {"": {"version": g["bindings"]}}}, indent=2
        ),
        "Cargo.lock": cargo_lock(g["bindings"], g["rust"], g["uniffi"]),
        # docs
        "docs/INSTALL.md": f"""# Installing

| Track | Languages | Example |
|---|---|---|
| Bindings | Python, Node.js | `{d["bindings"]}` (PyPI spells it `{pep(d["bindings"])}`) |
| UniFFI | C#, Go, C++ | `{d["uniffi"]}` |
| Rust crates | Rust | `{d["rust"]}` |

```bash
pip install --pre "fugle-marketdata=={pep(d["bindings"])}"
CGO_ENABLED=1 go get github.com/fugle-dev/fugle-marketdata-go@v{d["uniffi"]}
VERSION={d["uniffi"]}
TAG=v{d["bindings"]}     # the bindings release that shipped this UniFFI version
```

Pre-releases need an explicit version such as `fugle-marketdata=={pep(d["bindings"])}`.
""",
        "MIGRATION-0.9.md": f"# Migrating to 0.9.0 (bindings {d['bindings']}, uniffi {d['uniffi']})\n" + MIGRATION_BODY,
    }
    for rel, text in files.items():
        p = root / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(text)


def snapshot(root: Path) -> dict[str, str]:
    return {str(p.relative_to(root)): p.read_text() for p in root.rglob("*") if p.is_file()}


class Case(unittest.TestCase):
    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.root = Path(self._tmp.name)
        self._old_root = rv.ROOT
        rv.ROOT = self.root
        self.addCleanup(self._tmp.cleanup)
        self.addCleanup(setattr, rv, "ROOT", self._old_root)

    def run_cli(self, *argv: str) -> tuple[int, str]:
        out = io.StringIO()
        with contextlib.redirect_stdout(out), unittest.mock.patch.object(sys, "argv", ["release-versions.py", *argv]):
            code = rv.main()
        return code, out.getvalue()

    def versions(self) -> dict[str, str]:
        return rv.track_versions(rv.collect())


class TestPep440(unittest.TestCase):
    def test_conversion(self):
        self.assertEqual(rv.semver_to_pep440("3.0.0-rc.5"), "3.0.0rc5")
        self.assertEqual(rv.semver_to_pep440("3.0.0"), "3.0.0")
        self.assertEqual(rv.semver_to_pep440("1.2.3-beta.7"), "1.2.3b7")
        with self.assertRaises(ValueError):
            rv.semver_to_pep440("3.0.0-rc5")


class TestNextVersion(unittest.TestCase):
    def test_rc_increments(self):
        self.assertEqual(rv.next_version("bindings", "3.0.0-rc.4", "rc"), "3.0.0-rc.5")
        self.assertEqual(rv.next_version("rust", "0.9.0-rc.9", "rc"), "0.9.0-rc.10")

    def test_explicit(self):
        self.assertEqual(rv.next_version("uniffi", "0.2.0-rc.3", "0.3.0-rc.1"), "0.3.0-rc.1")

    def test_rc_on_non_rc_current_is_rejected(self):
        with self.assertRaisesRegex(ValueError, "not an rc"):
            rv.next_version("bindings", "3.0.0", "rc")

    def test_rc_only_rejects_stable_and_other_prereleases(self):
        self.assertTrue(rv.RC_ONLY)
        for bad in ("3.0.0", "3.0.0-beta.1"):
            with self.assertRaisesRegex(ValueError, "not a release candidate"):
                rv.next_version("bindings", "3.0.0-rc.4", bad)

    def test_garbage_is_rejected(self):
        with self.assertRaisesRegex(ValueError, "not a supported SemVer"):
            rv.next_version("bindings", "3.0.0-rc.4", "v3.0.0-rc.5")


class TestCheck(Case):
    def test_consistent_tree_passes(self):
        write_repo(self.root)
        code, out = self.run_cli("check")
        self.assertEqual(code, 0, out)
        self.assertIn("derived   js/index.js napi version check", out)
        self.assertIn("(6 sites)", out)  # 3 checks x 2 patterns

    def test_manifest_drift_fails(self):
        write_repo(self.root)
        p = self.root / "rust/Cargo.toml"
        p.write_text(p.read_text().replace(RUST, "0.9.0-rc.9"))
        code, out = self.run_cli("check")
        self.assertEqual(code, 1)
        self.assertIn("[rust] rust/Cargo.toml = '0.9.0-rc.9', expected '0.9.0-rc.3'", out)

    def test_stale_index_js_names_the_regenerate_command(self):
        write_repo(self.root, generated={"bindings": "3.0.0-rc.3"})
        code, out = self.run_cli("check")
        self.assertEqual(code, 1)
        self.assertIn("js/index.js napi version check = '3.0.0-rc.3' (6 sites), expected '3.0.0-rc.4'", out)
        self.assertIn("npm run build:debug", out)
        self.assertIn("js/package-lock.json", out)
        self.assertIn("npm install --package-lock-only", out)
        self.assertIn("Cargo.lock marketdata-js", out)
        self.assertIn("cargo update --workspace", out)

    def test_mixed_index_js_reports_every_version_seen(self):
        write_repo(self.root)
        (self.root / "js/index.js").write_text(index_js("3.0.0-rc.4", 2) + index_js("3.0.0-rc.2", 1))
        code, out = self.run_cli("check")
        self.assertEqual(code, 1)
        self.assertIn("= '3.0.0-rc.2, 3.0.0-rc.4' (6 sites)", out)

    def test_index_js_without_version_check_is_an_error(self):
        write_repo(self.root)
        (self.root / "js/index.js").write_text("/* auto-generated by NAPI-RS */\nmodule.exports = {}\n")
        code, out = self.run_cli("check")
        self.assertEqual(code, 1)
        self.assertIn("js/index.js napi version check: no version found", out)

    def test_stale_cargo_lock_for_rust_track(self):
        write_repo(self.root, generated={"rust": "0.9.0-rc.2"})
        code, out = self.run_cli("check")
        self.assertEqual(code, 1)
        self.assertIn("[rust] Cargo.lock fugle-marketdata-core = '0.9.0-rc.2', expected '0.9.0-rc.3'. Run `cargo update --workspace`", out)
        self.assertIn("[rust] Cargo.lock fugle-marketdata = ", out)
        self.assertNotIn("[bindings] Cargo.lock", out)

    def test_stale_install_md_points_at_the_file(self):
        write_repo(self.root, docs={"uniffi": "0.2.0-rc.2"})
        code, out = self.run_cli("check")
        self.assertEqual(code, 1)
        for label in ("INSTALL.md track table, UniFFI", "INSTALL.md go get ...@v<uniffi>", "INSTALL.md VERSION=<uniffi>"):
            self.assertIn(f"[uniffi] {label} = '0.2.0-rc.2', expected '0.2.0-rc.3'. Edit docs/INSTALL.md by hand.", out)
        self.assertNotIn("[bindings] INSTALL.md", out)

    def test_install_md_pep440_slots(self):
        write_repo(self.root, docs={"bindings": "3.0.0-rc.3"})
        code, out = self.run_cli("check")
        self.assertEqual(code, 1)
        self.assertIn("INSTALL.md fugle-marketdata==<PEP 440> = '3.0.0rc3' (2 sites), expected '3.0.0rc4'", out)
        self.assertIn("INSTALL.md TAG=v<bindings> = '3.0.0-rc.3', expected '3.0.0-rc.4'", out)

    def test_install_md_restructured_is_an_error_not_a_pass(self):
        write_repo(self.root)
        p = self.root / "docs/INSTALL.md"
        p.write_text(p.read_text().replace("TAG=v", "RELEASE_TAG=v"))
        code, out = self.run_cli("check")
        self.assertEqual(code, 1)
        self.assertIn("INSTALL.md TAG=v<bindings>: no version found where one was expected", out)

    def test_derived_checks_skipped_while_manifests_disagree(self):
        # A manifest error makes the track version undefined; derived noise
        # would only hide the real problem.
        write_repo(self.root, generated={"bindings": "3.0.0-rc.1"})
        p = self.root / "js/package.json"
        p.write_text(p.read_text().replace(BINDINGS, "3.0.0-rc.9"))
        code, out = self.run_cli("check")
        self.assertEqual(code, 1)
        self.assertIn("[bindings] Cargo.toml [workspace.package]", out)
        self.assertNotIn("js/index.js", out)

    def test_resolve_also_runs_derived_checks(self):
        write_repo(self.root, generated={"bindings": "3.0.0-rc.3"})
        code, out = self.run_cli("resolve", "--tag", f"v{BINDINGS}")
        self.assertEqual(code, 1)
        self.assertIn("npm run build:debug", out)


class TestMigrationHistory(Case):
    """MIGRATION-0.9.md: only line 1 is a version slot; the body's old versions are history."""

    def test_title_drift_is_reported(self):
        write_repo(self.root)
        p = self.root / "MIGRATION-0.9.md"
        p.write_text(p.read_text().replace(f"bindings {BINDINGS},", "bindings 3.0.0-rc.3,", 1))
        code, out = self.run_cli("check")
        self.assertEqual(code, 1)
        self.assertIn("MIGRATION-0.9.md title, bindings = '3.0.0-rc.3', expected '3.0.0-rc.4'. Edit MIGRATION-0.9.md by hand.", out)

    def test_historical_mentions_in_body_are_not_flagged(self):
        write_repo(self.root)
        body = (self.root / "MIGRATION-0.9.md").read_text()
        self.assertIn("3.0.0-rc.1 to rc.4", body)
        self.assertIn("3.0.0rc1", body)
        code, out = self.run_cli("check")
        self.assertEqual(code, 0, out)

    def test_title_pattern_moved_off_line_one_is_an_error(self):
        write_repo(self.root)
        p = self.root / "MIGRATION-0.9.md"
        p.write_text("<!-- preamble -->\n" + p.read_text())
        code, out = self.run_cli("check")
        self.assertEqual(code, 1)
        self.assertIn("MIGRATION-0.9.md title, bindings: no version found", out)

    def test_bump_rewrites_only_line_one(self):
        write_repo(self.root)
        before = (self.root / "MIGRATION-0.9.md").read_text()
        code, out = self.run_cli("bump", "--bindings", "rc", "--uniffi", "rc")
        self.assertEqual(code, 0, out)
        after = (self.root / "MIGRATION-0.9.md").read_text()
        self.assertEqual(after.split("\n", 1)[0], "# Migrating to 0.9.0 (bindings 3.0.0-rc.5, uniffi 0.2.0-rc.4)")
        self.assertEqual(after.split("\n", 1)[1], before.split("\n", 1)[1])  # body byte-identical
        self.assertIn("3.0.0-rc.1 to rc.4 dropped all of these", after)


class TestBump(Case):
    def test_rc_increment_all_tracks(self):
        write_repo(self.root)
        code, out = self.run_cli("bump", "--bindings", "rc", "--rust", "rc", "--uniffi", "rc")
        self.assertEqual(code, 0, out)
        self.assertEqual(self.versions(), {"bindings": "3.0.0-rc.5", "rust": "0.9.0-rc.4", "uniffi": "0.2.0-rc.4"})
        # every manifest, structurally re-read
        self.assertEqual(rv.check(rv.collect()), [])
        self.assertEqual(rv.toml("py/pyproject.toml")["project"]["version"], "3.0.0rc5")
        self.assertEqual(rv.toml("Cargo.toml")["workspace"]["dependencies"]["marketdata-core"]["version"], "0.9.0-rc.4")
        self.assertIn("<Version>0.2.0-rc.4</Version>", rv.read("bindings/csharp/MarketdataUniffi/MarketdataUniffi.csproj"))
        self.assertIn('getOrElse("0.2.0-rc.4")', rv.read("bindings/java/build.gradle.kts"))
        # docs followed
        install = rv.read("docs/INSTALL.md")
        self.assertIn("| Bindings | Python, Node.js | `3.0.0-rc.5` (PyPI spells it `3.0.0rc5`) |", install)
        self.assertIn("| UniFFI | C#, Go, C++ | `0.2.0-rc.4` |", install)
        self.assertIn("| Rust crates | Rust | `0.9.0-rc.4` |", install)
        self.assertEqual(install.count("fugle-marketdata==3.0.0rc5"), 2)
        self.assertIn("go get github.com/fugle-dev/fugle-marketdata-go@v0.2.0-rc.4", install)
        self.assertIn("\nVERSION=0.2.0-rc.4\n", install)
        self.assertIn("\nTAG=v3.0.0-rc.5     # the bindings release", install)
        self.assertNotIn(BINDINGS, install)
        # next steps name the generators and the changelog
        self.assertIn("npm run build:debug", out)
        self.assertIn("npm install --package-lock-only", out)
        self.assertIn("cargo update --workspace", out)
        self.assertIn("CHANGELOG.md", out)

    def test_explicit_version(self):
        write_repo(self.root)
        code, out = self.run_cli("bump", "--rust", "0.10.0-rc.1")
        self.assertEqual(code, 0, out)
        self.assertEqual(self.versions()["rust"], "0.10.0-rc.1")

    def test_tracks_are_independent(self):
        write_repo(self.root)
        before = snapshot(self.root)
        code, out = self.run_cli("bump", "--uniffi", "rc")
        self.assertEqual(code, 0, out)
        self.assertEqual(self.versions(), {"bindings": BINDINGS, "rust": RUST, "uniffi": "0.2.0-rc.4"})
        after = snapshot(self.root)
        changed = {k for k in before if before[k] != after[k]}
        self.assertEqual(
            changed,
            {
                "uniffi/Cargo.toml",
                "bindings/csharp/MarketdataUniffi/MarketdataUniffi.csproj",
                "bindings/java/build.gradle.kts",
                "docs/INSTALL.md",
                "MIGRATION-0.9.md",
            },
        )
        # only the uniffi slots moved inside INSTALL.md
        self.assertIn(f"TAG=v{BINDINGS}", after["docs/INSTALL.md"])
        self.assertIn(f"| Rust crates | Rust | `{RUST}` |", after["docs/INSTALL.md"])
        # bindings-only regeneration steps are not listed for a uniffi bump
        self.assertNotIn("npm run build:debug", out)
        self.assertIn("cargo update --workspace", out)

    def test_generated_files_are_never_edited(self):
        write_repo(self.root)
        before = snapshot(self.root)
        code, _ = self.run_cli("bump", "--bindings", "rc", "--rust", "rc", "--uniffi", "rc")
        self.assertEqual(code, 0)
        after = snapshot(self.root)
        for gen in ("js/index.js", "js/package-lock.json", "Cargo.lock"):
            self.assertEqual(before[gen], after[gen], gen)
        # ... which is exactly why check now fails and says what to run
        code, out = self.run_cli("check")
        self.assertEqual(code, 1)
        self.assertIn("npm run build:debug", out)
        self.assertIn("cargo update --workspace", out)

    def test_other_version_strings_in_touched_files_survive(self):
        write_repo(self.root)
        code, _ = self.run_cli("bump", "--bindings", "rc", "--rust", "rc")
        self.assertEqual(code, 0)
        cargo = rv.read("Cargo.toml")
        self.assertIn('# comment with version = "9.9.9" that must not be touched', cargo)
        self.assertIn('serde = { version = "1.0", features = ["derive"] }', cargo)
        self.assertIn('[tool.maturin]\nversion = "not-a-version"', rv.read("py/pyproject.toml"))
        self.assertIn('serde = { version = "1" }', rv.read("core/Cargo.toml"))

    def test_dry_run_writes_nothing(self):
        write_repo(self.root)
        before = snapshot(self.root)
        code, out = self.run_cli("bump", "--bindings", "rc", "--rust", "rc", "--uniffi", "rc", "--dry-run")
        self.assertEqual(code, 0, out)
        self.assertEqual(snapshot(self.root), before)
        self.assertIn("bindings  3.0.0-rc.4 -> 3.0.0-rc.5", out)
        self.assertIn("py/pyproject.toml (PEP 440)", out)
        self.assertIn("3.0.0rc4 -> 3.0.0rc5", out)
        self.assertIn("Dry run: nothing written.", out)

    def test_rc_only_refuses_stable_before_touching_anything(self):
        write_repo(self.root)
        before = snapshot(self.root)
        code, out = self.run_cli("bump", "--bindings", "3.0.0", "--uniffi", "rc")
        self.assertEqual(code, 1)
        self.assertIn("'3.0.0' is not a release candidate", out)
        self.assertEqual(snapshot(self.root), before)

    def test_refuses_when_manifests_already_disagree(self):
        write_repo(self.root)
        p = self.root / "rust/Cargo.toml"
        p.write_text(p.read_text().replace(RUST, "0.9.0-rc.9"))
        before = snapshot(self.root)
        code, out = self.run_cli("bump", "--bindings", "rc")
        self.assertEqual(code, 1)
        self.assertIn("Manifests disagree", out)
        self.assertEqual(snapshot(self.root), before)

    def test_missing_slot_aborts_before_writing(self):
        write_repo(self.root)
        p = self.root / "docs/INSTALL.md"
        p.write_text(p.read_text().replace("TAG=v", "RELEASE_TAG=v"))
        before = snapshot(self.root)
        code, out = self.run_cli("bump", "--bindings", "rc")
        self.assertEqual(code, 1)
        self.assertIn("INSTALL.md TAG=v<bindings> not found", out)
        self.assertEqual(snapshot(self.root), before)

    def test_post_write_check_failure_rolls_everything_back(self):
        write_repo(self.root)
        # Sabotage the write side of one manifest so the structural re-read
        # disagrees with the target: the csproj slot writes to a *different*
        # element than collect() reads.
        broken = [
            rv.Slot(s.path, s.label, r"<PackageId>([^<]+)</PackageId>", s.track) if "csproj" in s.path else s
            for s in rv.MANIFEST_SLOTS
        ]
        p = self.root / "bindings/csharp/MarketdataUniffi/MarketdataUniffi.csproj"
        p.write_text(p.read_text().replace("<Version>", "<PackageId>Fugle</PackageId>\n    <Version>"))
        before = snapshot(self.root)
        with unittest.mock.patch.object(rv, "MANIFEST_SLOTS", broken):
            code, out = self.run_cli("bump", "--bindings", "rc", "--rust", "rc", "--uniffi", "rc")
        self.assertEqual(code, 1)
        self.assertIn("MarketdataUniffi.csproj <Version> = '0.2.0-rc.3', expected '0.2.0-rc.4'", out)
        self.assertIn("every file has been restored", out)
        self.assertEqual(snapshot(self.root), before)  # bindings and rust edits rolled back too

    def test_exception_after_write_rolls_everything_back(self):
        write_repo(self.root)
        before = snapshot(self.root)
        real_collect = rv.collect
        calls = []

        def flaky_collect():
            calls.append(1)
            if len(calls) == 2:  # first call is the pre-bump check; second is the re-read after writing
                raise tomllib.TOMLDecodeError("boom", "", 0)
            return real_collect()

        with unittest.mock.patch.object(rv, "collect", flaky_collect):
            code, out = self.run_cli("bump", "--bindings", "rc", "--rust", "rc")
        self.assertEqual(code, 1)
        self.assertIn("TOMLDecodeError", out)
        self.assertIn("every file has been restored", out)
        self.assertEqual(snapshot(self.root), before)

    def test_keyboard_interrupt_mid_write_rolls_back_and_reraises(self):
        write_repo(self.root)
        before = snapshot(self.root)
        real_write = rv.write
        calls = []

        def interrupted_write(path, text):
            calls.append(path)
            if len(calls) == 3:
                raise KeyboardInterrupt
            real_write(path, text)

        with unittest.mock.patch.object(rv, "write", interrupted_write), self.assertRaises(KeyboardInterrupt):
            self.run_cli("bump", "--bindings", "rc", "--rust", "rc", "--uniffi", "rc")
        self.assertGreater(len(calls), 3)  # the rollback writes happened after the interrupt
        self.assertEqual(snapshot(self.root), before)

    def test_punctuation_after_a_doc_version_survives(self):
        write_repo(self.root)
        p = self.root / "docs/INSTALL.md"
        p.write_text(p.read_text() + f"\nSee `fugle-marketdata-go@v{UNIFFI}`. Also `fugle-marketdata=={rv.semver_to_pep440(BINDINGS)}`.\n")
        code, out = self.run_cli("check")
        self.assertEqual(code, 0, out)
        code, out = self.run_cli("bump", "--bindings", "rc", "--uniffi", "rc")
        self.assertEqual(code, 0, out)
        self.assertIn("See `fugle-marketdata-go@v0.2.0-rc.4`. Also `fugle-marketdata==3.0.0rc5`.", p.read_text())

    def test_noop_when_already_at_version(self):
        write_repo(self.root)
        before = snapshot(self.root)
        code, out = self.run_cli("bump", "--bindings", BINDINGS)
        self.assertEqual(code, 0)
        self.assertIn("already 3.0.0-rc.4, nothing to do", out)
        self.assertEqual(snapshot(self.root), before)

    def test_no_track_given(self):
        write_repo(self.root)
        code, out = self.run_cli("bump")
        self.assertEqual(code, 0)
        self.assertIn("Nothing to bump", out)


class TestAgainstRealRepo(unittest.TestCase):
    """The write side (MANIFEST_SLOTS) must address exactly what collect() reads, in the real tree.

    Everything else runs on a synthetic skeleton; this is the one place that
    notices when someone reorders Cargo.toml or pyproject.toml so a slot
    stops matching (or matches twice) while the structural read still works.
    """

    def test_each_manifest_slot_matches_collect_once(self):
        versions = rv.collect()
        for slot in rv.MANIFEST_SLOTS:
            with self.subTest(slot=slot.label):
                self.assertEqual(rv.slot_values(rv.read(slot.path), slot), [versions[slot.track][slot.label]])

    def test_each_doc_slot_matches_at_least_once(self):
        for slot in rv.DOC_SLOTS:
            with self.subTest(slot=slot.label):
                self.assertTrue(rv.slot_values(rv.read(slot.path), slot), f"{slot.label} no longer matches {slot.path}")


if __name__ == "__main__":
    unittest.main()
